[project]
name = "calculator"
version = "0.1.0"
description = "Calculator module"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
