[lint]
select = ["ALL"]
ignore = [
    "INP001",  # Ignore missing __init__.py for namespace packages, 
    "D100",  # Ignore missing module-level docstrings
    "D203", "D211",  # Conflicting rules about blank lines before class
    "D212", "D213",  # Conflicting rules about multi-line docstrings
    "S101",  # Ignore `assert` usage in tests
    "T201",  # Ignore `print` statements in Logger component
    "COM812", #Suggested by ruff to disable it to avoid unexpected behavior
]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "ANN001", "ANN201"]
