[project]
name = "logger"
version = "0.1.0"
description = "Logger module"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notifier"
    ]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
notifier = { workspace = true }