# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/python:3.12

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Print a test message"
          command: "echo The CI/CD pipeline has been successfully initiated."

  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: "Install UV"
          command: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: "Create virtual environment"
          command: |
            uv venv .venv
            echo 'export PATH="$HOME/project/.venv/bin:$PATH"' >> $BASH_ENV
      - run:
          name: "Install dependencies"
          command: |
            source .venv/bin/activate
            uv sync
      - run:
          name: "Run linting and formatting"
          command: |
            source .venv/bin/activate
            uvx ruff format .
            uvx ruff check .
      - persist_to_workspace:
          root: .
          paths:
            - .venv

  test:
    docker:
      - image: cimg/python:3.12
    environment:
      PYTHONPATH: .
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Ensure virtual environment exists"
          command: |
            if [ ! -d ".venv" ]; then
              echo "Virtual environment not found. Recreating..."
              uv venv .venv
              source .venv/bin/activate
              uv sync
            else
              source .venv/bin/activate
            fi
            echo 'export PATH="$HOME/project/.venv/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: "Execute test suite"
          command: |
            source .venv/bin/activate
            mkdir -p test-results
            python -m coverage run -m pytest tests/ --junitxml=test-results/junit.xml
            python -m coverage report
            python -m coverage xml
            python -m coverage html
      - run:
          name: "Run static analysis (mypy)"
          command: |
            source .venv/bin/activate
            uv pip install mypy  
            mypy --strict src/
      - run:
          name: "Enforce coverage threshold"
          command: |
            source .venv/bin/activate
            python -m coverage report --fail-under=90
      - run:
          name: "Execute nose2 tests (Optional)"
          command: |
            source .venv/bin/activate
            uv pip install nose2
            if command -v nose2 &> /dev/null; then  
              python -m nose2 --with-coverage
            else
              echo "nose2 is not installed. This step will be skipped."
            fi
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: coverage.xml

  report-results:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Summarize test results"
          command: |
            echo "Summary of test execution:"
            grep -o 'tests passed' test-results/junit.xml | wc -l | awk '{print "Number of passed tests: " $1}'
            grep -o 'failures' test-results/junit.xml | wc -l | awk '{print "Number of failed tests: " $1}'
      - run:
          name: "Summarize code coverage"
          command: |
            echo "Code coverage report:"
            cat coverage.xml | grep -o 'line-rate="[^"]*"' | head -n 1

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  ci-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - report-results:
          requires:
            - test
