version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    environment:
      PYTHONPATH: /home/circleci/project/src  # Add here too for build steps
    steps:
      - checkout
      - run:
          name: "Install UV"
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
      - run:
          name: "Setup environment"
          command: |
            uv venv .venv
            source .venv/bin/activate
            uv pip install -r requirements.txt
            uv pip install pytest mypy ruff coverage
      - persist_to_workspace:
          root: .
          paths:
            - .venv
            - src
            - tests

  test:
    docker:
      - image: cimg/python:3.12
    environment:
      PYTHONPATH: /home/circleci/project/src  # Critical for imports
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Activate environment"
          command: |
            source .venv/bin/activate
      - run:
          name: "Run tests"
          command: |
            pytest tests/ --junitxml=test-results/junit.xml --cov=src --cov-report=xml
      - run:
          name: "Type checking"
          command: |
            mypy --strict --config-file mypy.ini src/
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml

  report:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Coverage report"
          command: |
            python -m coverage report --fail-under=85
            python -m coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  build-test-report:
    jobs:
      - build
      - test:
          requires:
            - build
      - report:
          requires:
            - test