[project]
name = "calculator-impl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "calculator",
]

[tool.uv.sources]
calculator = { path = "../calculator", editable = true }
